require_relative './fetch_weather'
require_relative './fetch_stock'
require_relative './fetch_crypto'
require_relative './fetch_commodity'
require_relative './fetch_tank'
require_relative './fetch_water'
require_relative './fetch_sky_color'
