default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: m290_development

test:
  <<: *default
  database: m290_test

production:
  url: <%= ENV['DATABASE_URL'] %>
